version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRESE_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:postgres}
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /data/postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    command:
      -c shared_buffers=256MB
      -c max_connections=200
      -c listen_addresses='*'
  
#  pgadmin:
#    container_name: pgadmin_container
#    image: sss
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    networks:
#      - db_network

  rust_app:
    image: tauri-next:latest
    container_name: rust_app_container
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: postgresql://app_user:dev_only_pwd@postgres:5432/app_db
    depends_on:
      - postgres


