version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: info_db
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/

  rust_app:
    image: crud:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:abc123@postgres:5432/info_db
    depends_on:
      - postgres